### PR TITLE
Adding new Jobtypes to Documentation.  

### PR DESCRIPTION
**Pull request by dwhu**
Adding sections for:
- Script Jobs (https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/jobExecutor/ScriptJob.java)
- Python Jobs - Script (https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/jobExecutor/PythonJob.java)
- Ruby Jobs (https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/jobExecutor/RubyJob.java)

### CODE REVIEW

**Comment by dmeijboom** [comment]
This looks very helpfull to me.. I didn't know there was a Python or Ruby job-type. Can this be merged?

**Comment by dmeijboom** [comment]
Also maybe it would be nice to also state that if you want to use python3 on debian systems you can simply set the python variable in jobProps to python3 which then will be used as executable for python scripts.

**Comment by HappyRay** [comment]
These job types are not documented. I am curious if these job types over significant value over simply using the command job type.

**Comment by HappyRay** [comment]
These job types have been removed. #1431

**Pull request closed without merging**
