### PR TITLE
Fix for failing to kill a job due to a race condition

### PR DESCRIPTION
**Pull request by HappyRay**
Problem:

After a flow starts, kill the flow quickly.
The flow and the job will show as killed. However, the job actually runs
to completion.

Sample job log:
Logs:
25-07-2017 17:14:53 PDT IntegrationTest_jobCommand ERROR - Kill has been called.
25-07-2017 17:14:53 PDT IntegrationTest_jobCommand ERROR - Process has not yet started.
25-07-2017 17:14:53 PDT IntegrationTest_jobCommand ERROR - Failed trying to cancel job. Maybe it hasn't started running yet or just finished.
25-07-2017 17:15:03 PDT IntegrationTest_jobCommand INFO - Process completed successfully in 10 seconds.
25-07-2017 17:15:03 PDT IntegrationTest_jobCommand INFO - Finishing job IntegrationTest_jobCommand attempt: 0 at 1501028103180 with status KILLED

Analysis:

Jobrunner thread runs: azkaban.jobExecutor.utils.process
.AzkabanProcess#run

A jetty thread processes the kill command:

azkaban.jobExecutor.ProcessJob#cancel
azkaban.jobExecutor.utils.process.AzkabanProcess#softKill
azkaban.jobExecutor.utils.process.AzkabanProcess#checkStarted
here it throws exception, because the job process has not been created
yet at this point.

This exception is caught and ignored.
Users are informed that the kill action is completed and reflected in
the job and flow pages.

Fix:

Synchronize the killing thread and the jobrunner thread.
The jetty thread will wait for the job process to be created if needed
before killing the job process.

Scope of the fix:

This fix only addresses the synchronization issue between the killing Jetty thread and the jobrunner thread. It doesn't address the potential synchronization issues between the killing thread and the flowrunner thread e.g. There may be still some other race condition that causes a kill action to not kill a running job. 

====

This is a fix built on the idea proposed in #1289
The previous fix #1253 for the same race condition is not complete.

### CODE REVIEW

**Comment by jamiesjc** [comment]
LGTM. I'll pull your changes and run some integration test to verify it as well.

**Comment by HappyRay** [comment]
Thanks @jamiesjc !

**Comment by jamiesjc** [comment]
I've run integration test repeatedly and verified the fix from the job logs.

Job Logs
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Starting job IntegrationTest_jobCommand at 1502145082031
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - azkaban.webserver.url property was not set
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - job JVM args: -Dazkaban.flowid=IntegrationTest -Dazkaban.execid=19248 -Dazkaban.jobid=IntegrationTest_jobCommand
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Building command job executor. 
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand ERROR - Kill has been called.
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Memory granted for job IntegrationTest_jobCommand
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - 1 commands to execute.
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - effective user is: azktest
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Command: sleep 90
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Environment variables: {JOB_OUTPUT_PROP_FILE=/Users/jasun/AZNewDesign/azkaban/executions/19248/IntegrationTest_jobCommand_output_1600379015566666597_tmp, JOB_PROP_FILE=/Users/jasun/AZNewDesign/azkaban/executions/19248/IntegrationTest_jobCommand_props_1415711911832383526_tmp, KRB5CCNAME=/tmp/krb5cc__az_acceptance_test__IntegrationTest__IntegrationTest_jobCommand__19248__azktest, JOB_NAME=IntegrationTest_jobCommand}
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Working directory: /Users/jasun/AZNewDesign/azkaban/executions/19248
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - **The job is killed. Abort. No job process created.**
07-08-2017 15:31:22 PDT IntegrationTest_jobCommand INFO - Finishing job IntegrationTest_jobCommand attempt: 0 at 1502145082135 with status KILLED

**Comment by HappyRay** [comment]
Thanks @jamiesjc !

Did you also try delaying the kill command a little bit to see if the job process is killed?

**Comment by jamiesjc** [comment]
@HappyRay Yes, I've tried delaying the kill command and it also succeeds. 
I have shared a test in https://github.com/azkaban/azkaban/pull/1300#issuecomment-320924658, which will kill the flow after it starts. And we can add delays in between to simulate different scenarios.

**Pull request merged**
