### PR TITLE
build: run Travis build with --info flag to get more detailed output

### PR DESCRIPTION
**Pull request by HappyRay**
It's useful to see additional information. It's currently difficult to
debug a flaky test that only fails in Travis since there is no easy way
to see the test's console output.

### CODE REVIEW

**Comment by juhoautio** [comment]
So, does that mean that all of the test output (stdout, stderr, logger logs) are shown?

**Comment by HappyRay** [comment]
It appears so.

e.g.

```
azkaban.jobtype.JobTypeManagerTest > testBuildClass STANDARD_OUT
    2017/08/26 18:18:35.135 +0000 INFO [JobTypeManager] Job type plugin directory set. Loading extra job types from /tmp/junit9116303074802479980/jobtypes_test
    2017/08/26 18:18:35.156 +0000 INFO [JobTypeManager] Common plugin job props file /tmp/junit9116303074802479980/jobtypes_test/common.properties found. Attempt to load.
    2017/08/26 18:18:35.156 +0000 INFO [JobTypeManager] Common plugin load props file /tmp/junit9116303074802479980/jobtypes_test/commonprivate.properties found. Attempt to load.
    2017/08/26 18:18:35.158 +0000 INFO [JobTypeManager] Loading plugin anothertestjob
```
see 
https://travis-ci.org/azkaban/azkaban/builds/268728495?utm_source=github_status&utm_medium=notification

**Comment by HappyRay** [comment]
I will have this change checked in as soon as another repo maintainer approves this change. 
In the mean time, you should be able to do the same in your PR.

**Comment by juhoautio** [comment]
Awesome.

**Comment by HappyRay** [comment]
@kunkun-tang Thanks for your review!

**Pull request merged**
