### PR TITLE
After upgrading from 2.1 I no longer see anything in the Recently Fin…

### PR DESCRIPTION
**Pull request by arumugarani**
…ished tab #306

### CODE REVIEW

**Comment by fsi206914** [comment]
It works! We are not familiar with velocity. @arumugarani , May I know why **recentlyFinished.isEmpty()** doesn work? and what does **!$null.isNull** mean?

Thank you!

**Comment by arumugarani** [comment]
it should also work, but it should be !recentlyfinished.isEmpty :)
And more over in the place where recentlyfinished has been filled up has a
possible value of null if nothing is there to dispaly and hence I made the
same check as if "CurrentlyRunning" tab

**Comment by fsi206914** [comment]
LSGM. Will merge your request soon.

**Comment by arumugarani** [comment]
Please mark the bug #306 https://github.com/azkaban/azkaban/issues/306 as
closed

**Pull request merged**
