### PR TITLE
Update distributionUrl

### PR DESCRIPTION
**Pull request by Dshiv**
Was running gradlew build instalDist and kept getting a url error. This should fix it I believe.

### CODE REVIEW

**Comment by HappyRay** [comment]
https://services.gradle.org/distributions/ seems to be accessible and ./gradlew works for me. 
Could you point to the documentation that suggests this alternative URL should be used?

**Comment by Dshiv** [comment]
Sorry, It looks like there is a different issue with my setup a bit. I'm running the gradlew build installDist via docker with openjdk-8-jdk installed. At some point I was recieving errors saying that it could not download https://services.gradle.org/distributions/gradle-3.5.1-all.zip. I ran curl and saw the 302 HTTP response that that url gives. Closing.

**Comment by Dshiv** [comment]
I apologize for my lack of due diligence before opening a pull request.

**Comment by HappyRay** [comment]
No problem. Thanks for trying to fix an issue you observed.

**Pull request closed without merging**
