### PR TITLE
fix copyJSLibs must dependon bowerInstall (bowerInstall is not completed before copyJSLibs)

### PR DESCRIPTION
**Pull request by fsi206914**
Yesterday, we faced an issue that build folder (under web-server) doesn't have js files downloaded by bower plugin.

In the previous pull request commit #718 , bowerInstall and **copyJSLibs** are at the same dependency level. As a result, bowerInstall always takes longer time than **copyJSLibs**. JS lib files are often not ready before the copy. In this pull request, we enforce copyJSLibs has to depend on bowerInstall, in order to let bower js libraries are all set before coping them.

### CODE REVIEW

**Comment by HappyRay** [comment]
LGTM
I can't merge because of the test failure though.

**Comment by fsi206914** [comment]
Resolved the test failure problem in #724 . Will merge of #724 automatically make this pull request pass?

**Comment by HappyRay** [comment]
You will need to rebase anyway. That should trigger another build/test.

**Comment by fsi206914** [comment]
Merged.

**Pull request merged**
