### PR TITLE
Fix flow alert message

### PR DESCRIPTION
**Pull request by juhoautio**
The message for all flow alerts used to be this:

> Executor no longer seems to be running this execution. Most likely due to executor bounce.

Usually the alert comes because a job itself failed. It's confusing to suggest that executor node would've been restarted, when it's not.

### CODE REVIEW

**Comment by logiclord** [comment]
LGTM

**Comment by georgezhlw** [comment]
Juho, I think we could add flow status FAILED/KILLED to the error message. And it's not "seems", it's "really" :)

**Comment by juhoautio** [comment]
@georgezhlw, I added another commit:

1. Add flow status to list of reasons in flow failure alert message
  - Usually the status is FAILED or KILLED
2. A bit of better message about executor _really_ not running the flow anymore

**Comment by juhoautio** [comment]
@logiclord @georgezhlw how about pulling this in?

**Comment by logiclord** [comment]
@HappyRay can you please take a look ?

**Comment by HappyRay** [comment]
Thanks @juhoautio for the pull request!

I agree that this message is confusing. 

I assume you included the flow status so that users don't have to click the link to see if a flow has been killed or failed. 

The code is duplicated in two places. What do you think of changing the azkaban.executor.mail.DefaultMailCreator#createErrorEmail method to always include the flow status so that this extra information is included in both cases and also in other code paths that would call into this method?  

And remove the extra reasons from these two places. The last extra reason seems redundant. If a flow has failed or been killed, doesn't it imply it is no longer running?

===

Also could you make the change description a bit more descriptive like what you have in your comment? 

===
Could you include in your change description how you tested this change? Ideally a screenshot with the test result would be great.

**Comment by juhoautio** [comment]
Added commit here as well, but rather have a squashed single commit -> new PR: https://github.com/azkaban/azkaban/pull/680

**Pull request closed without merging**
