### PR TITLE
auto refresh joblog every 5 seconds

### PR DESCRIPTION
**Pull request by Codefor**
Currently the job log won't be refreshed until you manually click the Refresh button.

### CODE REVIEW

**Comment by Codefor** [comment]
CI ran failed because of maven:

Execution failed for task ':azkaban-common:compileJava'.
> Could not resolve all dependencies for configuration ':azkaban-common:errorprone'.
   > Could not resolve com.google.errorprone:error_prone_core:2.0.5.
     Required by:
         com.linkedin:azkaban-common:3.0.0
      > Could not resolve com.google.errorprone:error_prone_core:2.0.5.
         > Could not get resource 'https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.0.5/error_prone_core-2.0.5.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.0.5/error_prone_core-2.0.5.pom'.
               > Connection to https://repo1.maven.org refused

**Comment by davidzchen** [comment]
I have restarted the failed CI build.

**Comment by logiclord** [comment]
5 sec seems like a really short interval. Can you please increase to say 2 mins ?

**Comment by suvodeep-pyne** [comment]
Cleaning up unattended / old PRs

**Pull request closed without merging**
