### PR TITLE
use POST instead of GET for executing flow

### PR DESCRIPTION
**Pull request by wilson-lauw**
because GET has url length limitation, this will cause problem when we have a large flow, and we disable a lot of the job inside, as the disabled jobs list will need to be included in the request param.

### CODE REVIEW

**Comment by wilson-lauw** [comment]
Updated the documentation as well.

**Comment by ypadron-in** [comment]
Hi @wilson-lauw,

So sorry for the delays! 
Could you please update the curl example in the documentation [here](https://azkaban.readthedocs.io/en/latest/ajaxApi.html#execute-a-flow) to use the POST HTTP method instead? 

Also, could you please resolve the conflicts to merge this PR? I'm not sure why commit https://github.com/azkaban/azkaban/pull/2560/commits/6126379ef6386a630aa9068e9b652810ebeddd2e which belongs to PR #2549 is showing up in this PR.

**Comment by wilson-lauw** [comment]
let me check on that, seems like someone force push on the master branch on the main repo causing that commit to be gone from the master branch

**Comment by wilson-lauw** [comment]
I recreated the PR here: https://github.com/azkaban/azkaban/pull/2613

**Pull request closed without merging**
