### PR TITLE
Fix log level of printing plugin class name

### PR DESCRIPTION
**Pull request by juhoautio**
It's not an error, just informative logging.

### CODE REVIEW

**Comment by fsi206914** [comment]
Good catch!
LSGM.

**Comment by HappyRay** [comment]
@juhoautio Thanks for your contribution!

**Comment by juhoautio** [comment]
Thanks @HappyRay for merging some PRs by me.

**Comment by HappyRay** [comment]
@juhoautio you are welcome. I should thank you for your contribution instead.

I wish I had more time working with the community. I've been very busy at work lately.

**Pull request merged**
