### PR TITLE
Changed 'Succeed' to 'Success' in the filter. Maps to what the table doe...

### PR DESCRIPTION
**Pull request by Antall**
...s display

### CODE REVIEW

**Comment by erwa** [comment]
I think it should be "Succeeded", to match "Failed" and "Killed".

**Comment by Antall** [comment]
A flow that has completed successfully shows the status of 'Success' in the table, I thought the filter should represent what the table displays. Are you suggesting that the table should also show "Succeeded" in the status column?

**Comment by erwa** [comment]
Yeah, I think "Succeeded" makes more grammatical sense.

**Comment by Antall** [comment]
How do I run tests across the entire project?

**Comment by erwa** [comment]
Does `gradle test` in the root of the project work? I also think tests are automatically run when you do a `gradle distZip`. If you want to skip tests, you can do `gradle distZip -x test`.

**Comment by suvodeep-pyne** [comment]
Cleaning up unattended / old PRs

**Pull request closed without merging**
