### PR TITLE
disallow no action SLA

### PR DESCRIPTION
**Pull request by chengren311**
This PR is attempting to solve issue https://github.com/azkaban/azkaban/issues/1363.
Currently if we setup SLA but with no action specified, there will be no warning, and schedule page will show "has SLA" is true.
However, action should be required when setting up SLA. 

This PR added a non empty check on SLA actions when adding SLA for a schedule. Warning window will show up if action is not specified when setting SLA.
Old check was not checking the number of actions at all when updating SLA. The null check was used when uploading project logs.
Verified manually, but will automate the test in the internal integration test framework

### CODE REVIEW

**Comment by HappyRay** [comment]
The code looks fine to me.

Could you describe the issue in the change description to make it easier for readers?

Could you describe more details of the fix e.g. what's wrong with the existing code and how you fixed it? 

What's your test strategy? Can it be automated?

**Comment by chengren311** [comment]
@HappyRay updated the description.

**Comment by HappyRay** [comment]
Thanks.

Am I right that the old code's check if an action is specified is ineffective since the list object itself will never be null? The new code checks if the list is empty instead. It would be good to include this details in the commit message as well when you merge.

**Comment by chengren311** [comment]
@HappyRay the old check was not checking the number of actions at all when updating SLA. The null check was used when uploading project logs.

**Pull request merged**
