### PR TITLE
fix submitted user name for trigger when deserializing from json blob

### PR DESCRIPTION
**Pull request by chengren311**
submitted user should be deserialized from json instead of a constant value.

### CODE REVIEW

**Comment by HappyRay** [comment]
This doesn't look like a typo. Could you improve the change description?

**Comment by chengren311** [comment]
@HappyRay updated

**Comment by HappyRay** [comment]
Could you reference the pull request that introduced this bug?

**Comment by chengren311** [comment]
@HappyRay added in the change description.

**Pull request merged**
