### PR TITLE
#1947 wrong 'Host' header in http callbacks deleted.

### PR DESCRIPTION
**Pull request by vladislav-sidorovich**
Could you please accept this fix of issue #1947?

### CODE REVIEW

**Comment by vladislav-sidorovich** [comment]
I deleted 1 line of code. How the code coverage can be decreased? :)

**Comment by kunkun-tang** [comment]
@vladislav-sidorovich Tody AZ exists quite many flaky tests, and coverage is up and down occasionally. When we review PR, we mainly consider the commit's coverage.

**Comment by kyrill007** [comment]
Dear Azkaban maintainers, what does it take to get this pull request merged into the main branch? We're facing the same issue and it is fairly critical for us. This fix does it. Thank you! Note that this pull request fixes issue https://github.com/azkaban/azkaban/issues/1950.

**Comment by juhoautio** [comment]
👍 for this change.

I don't believe this change has anything to do with the decreased coverage. It's probably just that the tests have some randomness factor in what code gets executed, and as a result coverage can fluctuate between different test runs.

**Comment by vladislav-sidorovich** [comment]
I will. 
Thank you

**Comment by HappyRay** [comment]
Thank you for your contribution!

**Pull request merged**
