### PR TITLE
Update codestyle setup guide in the README

### PR DESCRIPTION
**Pull request by HappyRay**
* Point to the intellij's guide.
* Users should be able to use import code style features instead.
* Advised against turning on "Remove unused suppress warning
annotation" option in the save actions plugin since it seems to be
unreliable.

### CODE REVIEW

**Comment by HappyRay** [comment]
Thanks @chengren311

**Comment by chengren311** [comment]
@HappyRay what's wrong with "Remove unused suppress warning annotation"

**Comment by HappyRay** [comment]
When I added a suppress warning annotation for a parameter, this plugin incorrectly removed it.

**Comment by HappyRay** [comment]
see https://github.com/azkaban/azkaban/pull/1147/commits/717445eaca91e4509aa27bdc745dc87a9aa31f39

**Pull request merged**
