### PR TITLE
[dev-email-errors] Email errors inline or attached

### PR DESCRIPTION
**Pull request by kaneda**
- Updated https://github.com/azkaban/azkaban/pull/308 to take in a max lines, so that inline emails don't exceed 5 errors by default
- Ensure that these settings default to off

### CODE REVIEW

**Comment by suvodeep-pyne** [comment]
Cleaning up unattended / old PRs

**Comment by kaneda** [comment]
@suvodeep-pyne it's not unattended, I asked for review of this a dozen times under the associated issue.

**Comment by ameyamk** [comment]
Unit tests?

**Comment by kaneda** [comment]
@ameyamk I can certainly write some

**Pull request closed without merging**
