### PR TITLE
Make FileIOUtils.createDeepHardlink() platform independent

### LINKED ISSUE #636: FileIOUtils.createDeepSymlink is platform specific
FileIOUtils.createDeepSymlink calls out to the system shell to create symlinks.  This is platform specific code which prevents Azkaban from working correctly on systems such as windows.

The core NIO libraries in java can achieve the same result in a platform independent fashion.

Pull request to follow.

### PR DESCRIPTION
**Pull request by bmsq**
Fixes #636.

Replaced FileIOUtils.createDeepSymlink() with a platform independent implementation that uses the Java NIO library.

### CODE REVIEW

**Comment by bmsq** [comment]
Um... this pull request has triggered a build failure (specifically on JDK1.8) but the test case which failed doesn't appear to have anything to do with my change: 
azkaban.execapp.event.BlockingStatusTest > testMultipleWatchers FAILED

I'm more than happy to fix this CI issue but I have no idea how this is related to my change.  Anyone care to comment?

**Comment by HappyRay** [comment]
@chengren311 is this PR still useful after your change in #894?

**Comment by bmsq** [comment]
@HappyRay I created this pull request after porting Azkaban for use on Windows servers (we use it on multiple client sites). Unfortunately, the existing use of "ln" is not portable, hence the need for this PR.

This PR, along with several others that I raised at the time, have been sitting here for a year. I'm happy to update this PR to create a hard link in a platform independent way but I won't bother if you don't think anyone will ever review it.

**Comment by chengren311** [comment]
@HappyRay this looks useful, and i'm willing to review it. @bmsq would you mind updating the PR with latest master and make sure the build goes through? Thanks for the contribution.

**Comment by HappyRay** [comment]
Sorry @bmsq for not responding to your PR. We need to improve our turn around time. Given other priorities, reviewing PRs especially the ones we don't have an immediate need sometimes fall through the cracks.

**Comment by bmsq** [comment]
No worries, i just didn't want to expend effort if it wasn't going to be useful. I'll see if I can sort this out over the weekend.

**Comment by HappyRay** [comment]
Thanks. There is no rush.

**Comment by chengren311** [comment]
@bmsq hi are you still interested in this PR.
@HappyRay I think we have a strong need for this. We are running into this issue when copying hard link for a project with few thousands of files:
https://stackoverflow.com/questions/11289551/argument-list-too-long-error-for-rm-cp-mv-commands

**Comment by bmsq** [comment]
Sorry about the slow response on this, I've been busy at work and home.

I've rebased with the latest master branch and updated to create hard links using NIO.  Unfortunately, I haven't been able to test this locally as the latest gradle scripts don't work on my windows machine (something about a node-linux dependencies) .  The Travis build suggest that this passes the related unit tests but you might want to verify before merge.

I don't have time to resolve it now but I will report back about windows compatibility when I've had the time to update the gradle script to be cross platform.

**Comment by chengren311** [comment]
@bmsq thanks for your contribution. It seems this PR contains thousands of changed files. I think you can open a new clean PR based on latest master with your change only.

**Comment by bmsq** [comment]
Ah, I must have done something stupid during the rebase. I'll get this sorted shortly.

Sorry about that

**Comment by chengren311** [comment]
@bmsq  thanks for your contribution! We have merged another similar PR(https://github.com/azkaban/azkaban/pull/1583) given the urgency to solve the issue.  Let me know if you have any feedback regarding this PR.

**Pull request closed without merging**
