### PR TITLE
Fixes "Auto Pan Zoom" option in the flow graph view.

### LINKED ISSUE #634: Auto Pan Zoom button does not work in Graph UI
When using the Job Filter in the left hand side of the flow graph, the "Auto Pan Zoom" option does not work.

Pull request to follow.

### PR DESCRIPTION
**Pull request by bmsq**
Fixes #634 

Selecting the "Auto Pan Zoom" button while using Job Filters in the Flow Graph View causes a javascript error.

This PR removes the "transform" variable which is the source of the issue but is never used.

### CODE REVIEW

**Comment by fsi206914** [comment]
@bmsq May we know why removing transform assignment is able to fix this Auto Pan Zoon bug?

**Comment by bmsq** [comment]
No worries.

getTransformToElement() is not a valid function for an SVG node.  When the JavaScript hits this line, it raises an error and doesn't execute the remainder of the function which prevents auto pan and zoom from working as expected.  

I was going to guess what the function was expected to do and implement a standards compliant equivalent. However, this function is called and assigned to a local variable which is redundant and never used.  The simple fix is to remove the variable and the broken call to getTransformToElement().

We auto generate a large flow containing +400 jobs with more than a 1,000 dependencies, so the search feature with auto pan and zoom is pretty critical for navigating the graph.

**Comment by fsi206914** [comment]
LGTM. Thanks @bmsq for the explanation.

**Comment by HappyRay** [comment]
Any reason why this one was not merged? @kunkun-tang

**Comment by kunkun-tang** [comment]
This issue is already fixed in #1338 . Closing

**Comment by HappyRay** [comment]
Thank @kunkun-tang

**Pull request closed without merging**
