### PR TITLE
Restore loadFlow API without stats

### PR DESCRIPTION
**Pull request by wyukawa**
loadFlow API was removed in https://github.com/azkaban/azkaban/pull/1182

But, there is no API to  get all schedule data.

I think that loadFlow API without stats will be acceptable.

### CODE REVIEW

**Comment by jamiesjc** [comment]
LGTM. If you still need to use that API, we would like to keep it for your convenience. Thanks for removing the stats as well.

**Comment by wyukawa** [comment]
@HappyRay Could you please take a look at this pull request when you get a chance?

**Comment by HappyRay** [comment]
@jamiesjc?

**Comment by jamiesjc** [comment]
I've reviewed the change and it looks good. Will merge it now.

**Comment by wyukawa** [comment]
Thanks!

**Pull request merged**
