### PR TITLE
Refactoring only: extract SLA parsing to new SlaRequestUtils

### PR DESCRIPTION
**Pull request by juhoautio**
This is groundwork for https://github.com/azkaban/azkaban/issues/2509: _Support SLA options in execute API_.

Just moved the code into a util class so that it can be next adjusted to be used also in `ExecutorServlet`.

### CODE REVIEW

**Comment by juhoautio** [comment]
@djaiswal83 how about this?

**Comment by djaiswal83** [comment]
Let me take a look.

**Comment by juhoautio** [comment]
@djaiswal83 thanks for approving, can this be merged? I don’t have merge permissions.

**Comment by juhoautio** [comment]
The larger change is also already submitted at https://github.com/azkaban/azkaban/pull/2523

**Comment by djaiswal83** [comment]
I keep it open for sometime just incase someone else wants to chime in.
Will merge it soon.

**Pull request merged**
