### PR TITLE
Removing non functional distribution tasks for azkaban-test

### PR DESCRIPTION
**Pull request by suvodeep-pyne**
The distribution tasks for azkaban-test were pointing to an invalid directory and were not resulting in any artifacts. Removing this dead code. The zip / tar archives are not used anywhere else in the project.

### CODE REVIEW

**Comment by suvodeep-pyne** [comment]
@fsi206914 Hey Liang, travis build fails a bunch of times for node js. Is this a known issue?
On restart, it works fine.

**Comment by fsi206914** [comment]
I even don't realize we have this folder! We should remove it. LGTM!

**Comment by HappyRay** [comment]
LGTM
It appears that this project is not complete. The test resources may still be useful?

**Comment by suvodeep-pyne** [comment]
The test resources are being used. It's just the distribution tasks which
are not. Also, if you notice the distribution job configuration in the
gradle script, the file locations in the script are incorrect. That's the
reason it doesn't generate those artifacts. And following that our internal
systems complain about missing artifacts.

That's why I want to delete them.

**Pull request merged**
