### PR TITLE
Switch to Guava Cache implementation.

### LINKED ISSUE #505: CacheTest.testLRU is failing
Stack trace:

```
java.lang.AssertionError: expected:<null> but was:<val1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at azkaban.utils.cache.CacheTest.testLRU(CacheTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Depends on:

* [ ] #552 Use Guava Cache implementation

### LINKED ISSUE #552: Use Guava Cache implementation
Currently, Azkaban has a custom implementation of an in-memory cache. There are a number of issues with the current implementation, namely the wrong element can be evicted if element accesses happen close together (see #505).

Because the Azkaban implementation is not doing anything special, it is better to just use Guava's Cache implementation instead.

### PR DESCRIPTION
**Pull request by davidzchen**
* Remove Azkaban's custom Cache implementation and switch SessionCache to
  use Guava's Cache implementation.
* Remove CacheTest.

Fixes #552
Fixes #505

### CODE REVIEW

**Comment by davidzchen** [comment]
FYI see documentation about Guava's Cache implementation here: https://github.com/google/guava/wiki/CachesExplained

**Comment by davidzchen** [comment]
Ping.

**Comment by davidzchen** [comment]
Ping. Can somebody take a look at this?

**Comment by hluu** [comment]
LGTM.  

Is Google actively use Guava Cache implemetation?

We should of use Gauva's Cache from day one.

**Comment by davidzchen** [comment]
Thanks for reviewing, @hluu!

Yes, Guava Cache is widely used here at Google as well as our open source projects, such as [Bazel](https://github.com/bazelbuild/bazel/search?utf8=%E2%9C%93&q=com.google.common.cache&type=Code), our build system, which I also contribute to. :)

According to @rbpark, Azkaban originally used [ehcache](http://www.ehcache.org/). However, it turns out that ehcache would [phone home](https://www.google.com/webhp#q=ehcache+phone+home) to check for updates, which is a very unusual behavior for a library. As a result, ehcache was ditched for a custom Cache implementation.

Guava actually provides a lot of very useful data structures. Unfortunately, not all of them are very well known in the open source world. :)

**Pull request merged**
