### PR TITLE
Test cleanup: simplify prepareProject usage

### PR DESCRIPTION
**Pull request by juhoautio**
Now takes String instead of File.

Discussed at https://github.com/azkaban/azkaban/pull/1151#discussion_r120014278.

### CODE REVIEW

**Comment by HappyRay** [comment]
This appears to be another random failure

I am concerned that there may be more.

azkaban.execapp.FlowRunnerTest2 > testCancel FAILED
    java.lang.NullPointerException
        at azkaban.executor.ExecutableFlowBase.isFlowFinished(ExecutableFlowBase.java:398)
        at azkaban.execapp.FlowRunnerTestBase.lambda$assertThreadShutDown$0(FlowRunnerTestBase.java:32)
        at azkaban.execapp.FlowRunnerTestBase$$Lambda$9/1157486615.apply(Unknown Source)
        at azkaban.execapp.FlowRunnerTestBase.waitFlowRunner(FlowRunnerTestBase.java:42)
        at azkaban.execapp.FlowRunnerTestBase.assertThreadShutDown(FlowRunnerTestBase.java:31)
        at azkaban.execapp.FlowRunnerTest2.testCancel(FlowRunnerTest2.java:729)

**Comment by juhoautio** [comment]
Valid concern. I'll try to replicate the random failures by running the test multiple times in a row.

**Comment by HappyRay** [comment]
Could you take a look at #1156 so that we can stabalize the master branch?

**Comment by juhoautio** [comment]
Looks like that error came from a synchronization issue, the way how `ExecutableFlowBase#isFlowFinished` works. I'm going to fix this by not calling that method but checking the flow finishing in another way.

**Comment by HappyRay** [comment]
Thanks. While you are investigating, could you approve #1156 so that the master is stable?

**Comment by juhoautio** [comment]
Fix for that test failure is here: https://github.com/azkaban/azkaban/pull/1158

**Comment by HappyRay** [comment]
I thought more about this change. 
I am not convinced that on balance this change is better. 
I understand that the caller of this method has to do less work. 
The benefit, however, is that it is more explicit to the readers what the contract is. i.e. this string is a path to a file.

**Comment by juhoautio** [comment]
Yeah, I was thinking the same thing. Closing.

**Comment by HappyRay** [comment]
Thanks. I appreciate that you have an open mind. 
I hope my objection didn't cost you too much time.

**Pull request closed without merging**
