### PR TITLE
update doc for SLA change

### PR DESCRIPTION
**Pull request by chengren311**
update related doc for https://github.com/azkaban/azkaban/pull/1092

### CODE REVIEW

**Comment by HappyRay** [comment]
Is it worth adding the version information when this change was introduced? Otherwise LGTM

**Comment by chengren311** [comment]
@HappyRay is this necessary? it seems version is not mentioned anywhere in this doc.  This doc is always referring to latest version.

**Comment by HappyRay** [comment]
It can help users who are not using the latest version. 
What's the downside?

**Comment by HappyRay** [comment]
It's less of a concern for users who deploys new versions regularly.

**Comment by chengren311** [comment]
downside is we change the convention/implication of this doc. If we do this, this will give users impression that If version is not specified, every az version works as documented. But it's not actually the case.

**Comment by HappyRay** [comment]
Some projects publish versioned docs. Maybe something to consider in the future. 
Just a suggestion. 

We can evaluate this enhancement later.

**Comment by chengren311** [comment]
@HappyRay ok, do you have other comments regarding this PR?

**Comment by shuzhang1989** [comment]
lgtm, but agreed with @HappyRay that we need some sort of format guide of writing docs.

**Comment by HappyRay** [comment]
LGTM

**Pull request merged**
