### PR TITLE
Remove e.printStackTrace

### PR DESCRIPTION
**Pull request by HappyRay**
Replace them with the logger.error call

### CODE REVIEW

**Comment by li-afaris** [comment]
It looks like the intent to move the stack trace from the HTTP reply into the host logs?  Why not have the stack trace in both places?  While not frequently used, our documentation does reference `WEBSERVER_URL/executor?ajax=...`

**Comment by HappyRay** [comment]
@li-afaris 
The error out goes to a different log file. Is there any reason not to use the standard log4j config to capture such error logs?

What are the benefits to log the same in both places?

> While not frequently used, our documentation does reference WEBSERVER_URL/executor?ajax=...

What do you mean?

**Comment by li-afaris** [comment]
> What are the benefits to log the same in both places?

My understanding is that e.printStackTrace would be printed to STDOUT and this could be a bad premise on my part.  But if the stack trace is printed to STDOUT, then the stack trace would be displayed to the client or browser accessing the API.  

> What do you mean?

I mentioned the documentation because people occasionally have the need to access the API through a web browser.   As a web browser can be another api client, printing a stack trace to the client could be useful. 

If I'm wrong about e.printStackTrace output going to the client accessing the API, then your change is good.

**Comment by HappyRay** [comment]
I see. No,  the error output won't be returned to clients.

**Pull request merged**
