### PR TITLE
remove job runner from active job runner list when job finishes

### PR DESCRIPTION
**Pull request by chengren311**
activeJobRunners maintains all active job runners, so we should remove inactive job runners when job finishes. As a consequence, activeJobRunners will keep queuing up and querying activeJobRunners by job name will return invalid job runner. This PR fixes this issue.

### CODE REVIEW

**Comment by HappyRay** [comment]
Could you describe why this change is needed?

**Comment by chengren311** [comment]
@HappyRay @kunkun-tang added more explanation. But I do think the change is self-explanatory.

**Comment by HappyRay** [comment]
How did the issue manifest itself? What problems will users or operators observe?

**Comment by chengren311** [comment]
@HappyRay the issue surfaced when jobs were not killed successfully by SLA in occasion cases. It turned out it's killed by an invalid job runner returned by querying the active job runner by job id.

**Comment by HappyRay** [comment]
I am not sure I follow. What's the sequence of the events?

And before your change, how was the list cleaned up?

**Comment by chengren311** [comment]
@HappyRay 
No one cleaned the list up.
We can talk offline.

**Comment by HappyRay** [comment]
Thanks for adding additional context.

**Pull request merged**
