### PR TITLE
Open quartz-scheduler.org links in new tab

### PR DESCRIPTION
**Pull request by ismailsimsek**
its better option to open quartz-scheduler.org links in new tab instead leaving  azkaban page?

### CODE REVIEW

**Comment by chengren311** [comment]
@ismailsimsek thanks for the contribution! would you mind posting an before-after screenshot?

**Comment by ismailsimsek** [comment]
first image showing current behavior. with first one when going back one page JS popup is gone and you need to tiger scheduling action from beginning. but scheduling options are still saved somehow.

second one is new behaviors which is opening link in new tab.  

screen shot 2018-02-15 at 08 56 24

New 
screen shot 2018-02-15 at 09 18 19

**Comment by chengren311** [comment]
@ismailsimsek thanks.

**Comment by ismailsimsek** [comment]
Thank you all for the new features and improvements

**Pull request merged**
