### PR TITLE
Issue #564 - Improve error message of scheduleFlow API

### PR DESCRIPTION
**Pull request by wyukawa**
https://github.com/azkaban/azkaban/issues/564

### CODE REVIEW

**Comment by juhoautio** [comment]
Hey that's really useful 👍

**Comment by wyukawa** [comment]
Rebase for master changes.

ping.

**Comment by HappyRay** [comment]
Thanks. 

Merged since the API design issue/question is an existing one.

**Comment by wyukawa** [comment]
Thank you for merging.

My opinion is as follows.

Hmm, in my current usage, I use /manager API with project name, as result I get project ID.
https://github.com/wyukawa/eboshi/blob/master/eboshi/project.py

And then I use /schedule API with project name and project ID.
https://github.com/wyukawa/eboshi/blob/master/eboshi/add_schedule.py

Although current API desigin requires more cost because project ID is necessary, I don't think about introducing more opportunities for clients to make mistakes.

And compatibility is important.

Thanks

**Comment by HappyRay** [comment]
Isn't there an opportunity for clients to specify an inconsistent project name and project ID to this API? In this case, the cost of such mistake seem to only affect logging. Would it be better to ignore the project name parameter and get the name from the project object directly?

**Comment by fsi206914** [comment]
@HappyRay It makes full senses to me. I got confused when I was reading this part of code.

**Comment by wyukawa** [comment]
+1

**Pull request merged**
