### PR TITLE
Improve condition on status whether to show job log links

### PR DESCRIPTION
**Pull request by juhoautio**

### CODE REVIEW

**Comment by juhoautio** [comment]
@djaiswal83 @burgerkingeater would you have time to review?

**Comment by juhoautio** [comment]
@djaiswal83 sorry but where, and what should the comment say?

**Comment by djaiswal83** [comment]
@juhoautio something like "show job logs when ....." Basically, word out the condition.
Also, please use "!==" instead of "!=" for better type safety.

**Comment by juhoautio** [comment]
@djaiswal83 done.

**Comment by juhoautio** [comment]
@djaiswal83, @jamiesjc could you merge this?

**Pull request merged**
