### PR TITLE
WIP: Implement unit tests for Emailer & EmailMessage

### PR DESCRIPTION
**Pull request by juhoautio**
These were previously ignored. Some refactoring was needed to inject dependencies.

Builds on https://github.com/azkaban/azkaban/pull/1663 (1st commit is the same) – for the actual scope of this PR, see the 2nd commit only: https://github.com/azkaban/azkaban/pull/1664/commits/972e43e2747cd2e0f95b4a4c34ea3a7d7c3beec3

### CODE REVIEW

**Comment by chengren311** [comment]
thanks! If i understand your change description correctly, https://github.com/azkaban/azkaban/pull/1663 is a subset of this PR? so we will only need to review  https://github.com/azkaban/azkaban/pull/1663?

**Comment by juhoautio** [comment]
I think it’s much easier to grasp if #1663 is dealt with first, separately. Usually at least @HappyRay has preferred splitting changes to individual pull requests to make it easier to follow.

**Comment by HappyRay** [comment]
Thanks @chengren311 for the review!

@juhoautio I am sorry for the delay in reviewing your changes. I have been assigned some high priority work that I may not be available to do reviews for a while.

**Comment by juhoautio** [comment]
Replaced by https://github.com/azkaban/azkaban/pull/1691

**Pull request closed without merging**
