### PR TITLE
Add Kill button in the currently running tab of Executing Flows

### PR DESCRIPTION
**Pull request by arumugarani**

### CODE REVIEW

**Comment by chengren311** [comment]
@arumugarani, would you mind posting images of before and after UI so that we can view this change more easily?

**Comment by arumugarani** [comment]
before_adding_killbtn
after_adding_killbtn

**Comment by arumugarani** [comment]
Added the images

**Comment by kunkun-tang** [comment]
The change proposal looks much sense to me. I often thought we should have this feature.

**Comment by arumugarani** [comment]
When will you merge this?

**Pull request merged**
