### PR TITLE
Unclosed Stream Causes Memory Leak

### PR DESCRIPTION
**Pull request by XinhhD**
Recently I tested azkaban with a very high concurrency.(tag 3.90)
Among the testing, azkaban server was always killed by OOM-Reaper which is a Linux memory protection mechanism.
By debuging with some perf-tools, I finally find it was the reason by unclosed Gzip stream.
After fixing it, server will not be killed by OOM-reaper again.

### CODE REVIEW

**Comment by XinhhD** [comment]
It still an unfixed issue in lastest code which can be a serious problem in bussiness enviroment.

**Comment by XinhhD** [comment]
#3026 this issue
@rjurney

**Review by ismailsimsek — APPROVED** [review]

**Review by ypadron-in — APPROVED** [review]
Good catch! Thanks a lot @XinhhD!

I'm curious about how you debugged this issue. Could you share the tools you used and if possible, perhaps elaborate a bit on how you detected this bugt?

**Comment by XinhhD** [comment]
> Good catch! Thanks a lot @XinhhD!
> 
> I'm curious about how you debugged this issue. Could you share the tools you used and if possible, perhaps elaborate a bit on how you detected this bugt?

First, I built 10,000 flows to test azkaban. These flows will be triggered at the same time ( eg. once half hour).

**Pull request merged**
