### PR TITLE
Added runtime dependencies for KafkaAppender to gradle build (#770)

### PR DESCRIPTION
**Pull request by KyleFung**
Some jar dependencies are needed to use the KafkaAppender in Log4j. These were added to the list of runtime dependencies.

### CODE REVIEW

**Comment by HappyRay** [comment]
I believe we have to use the internal version of Kafka. Have you check with the Kafka team?

**Comment by KyleFung** [comment]
The internal version of Kafka should be able to communicate with the external version of Kafka. I've also tested this using the external Kafka on our machines and they work fine.

**Comment by suvodeep-pyne** [comment]
Just recording what was discussed offline.

This code introduces compile time dependencies on Kafka. I'm just wondering whether that's the best way to go.

**Comment by KyleFung** [comment]
Closing this as if people want to use Kafka at run time, they should include the runtime dependency in themselves.

**Pull request closed without merging**
